### ISSUE TITLE
Tip 1320 on Top Queries shows up always and doesn't include query_id from Query Store

### ISSUE THREAD

**Issue by rgward** [microsoft/azure-sql-tips#28]
I ran the tips script on a few databases that I had not even used in some time and this tip showed up for each of them, including a serverless database that was previously paused.

Not sure if the intention of this script is to ALWAYS show the queries that consume most resources or actually show a problem.

In addition, if I wanted to drill into what these results show me it doesn't show query_id from the Query Store which is the default key to look at when looking at Top Resource Consuming Queries report

**Comment by dimitri-furman** [comment]
The intent is to simply show top queries, which by definition always exist when *any* queries have run. Admittedly, we may want to only show this tip conditionally, but I am not sure what the logic should be to do so without omitting it unintentionally when it would be useful. Perhaps we should simply augment the description to say that you will always see this.

We intentionally group by `query_hash`, because otherwise identical queries with different parameter definitions will be separate, which can change the overall ranking. In the wiki description, there is a query to map `query_hash` to `query_id`. Also, if there is only one `query_id` per `query_hash`, we do include it in the details. Same treatment for `plan_id`.

**Comment by denzilribeiro** [comment]
I agree with Dimitri query_hash is better, ideally we should have a report and view by query_hash too in Query store IMHO.

**Comment by dimitri-furman** [comment]
When there are multiple `query_id` per `query_hash`, we could show an arbitrary one in addition to saying that there are multiple matches. Would that be better?

**Comment by dimitri-furman** [comment]
Changing it to this format:
`query hash: 0x5F9043DBAAEBB1FF, query_id: 140 (+1), plan_id: 44 (+1), CPU time rank: 1, duration rank: 2, ...`

here there is one more `query_id` besides 140, and one more `plan_id` besides 44.

**Comment by rgward** [comment]
Dimitri,

I agree with both of you on query_hash but I also wanted an easier way to lookup the query from your tips in both Query Store and Query Performance Insights from the portal. Your proposal seems reasonable. I would definitely add more in the wiki that these results ALWAYS show up even if there is no performance problem.

**Comment by denzilribeiro** [comment]
In the wiki also can give a Query store query to get all query ID's /plan_ids for a specific query_hash

**Comment by dimitri-furman** [comment]
I updated the wiki for 1320 accordingly, please take a look.

**Comment by rgward** [comment]
This helps explain things much better. One thing you might add though in the beginning paragraph is that the queries used by the tips query may show up in the ranking. I cleared the query store and ran your script. This rule showed one query which I think was run by the tips query.  The Query Store report actually showed two queries. Not sure if the other run was from the tips script.

**Comment by dimitri-furman** [comment]
Makes sense, added that.
