### ISSUE TITLE
Allow checks to show "failed due to permissions" instead of not running any of it

### ISSUE THREAD

**Issue by wsmelton** [microsoft/azure-sql-tips#34]
In many environments, an admin is not an admin of the whole Azure SQL server and only the DB; or a developer wants to validate the database level items only.

The script as-is fails if **any** system view is not accessible without allowing us to run checks against a database. Splitting these into two catch blocks and simply show the checks that failed due to permissions will still offer users the ability to see improvements/things to fix instead of not knowing any of them.

**Comment by wsmelton** [comment]
I adjusted this script to remove the try/catch so I can see what returns just for the database level and I only see it return compatibility warning and just returning query hashes for "top queries" to check.

It would be nice if the tips table was expanded to include which checks apply to Azure SQL DB, MI, or both. I'm sure that is a vast difference in what can be checked based on the glance at the tips in the script.

**Comment by dimitri-furman** [comment]
Thanks for suggestions @wsmelton. Coincidentally :), the latest commit (yet to be released) adds support for running the script with only VIEW DATABASE STATE permission that a database owner would have, and without any server-level permissions. The [wiki](https://github.com/microsoft/azure-sql-tips/wiki/Azure-SQL-Database-tips#permissions) has been updated accordingly.

The suggestion of showing which tips were not evaluated because of insufficient permissions is great, we will add that. Right now there is just one tip like that, but that could change.

It is entirely possible that the script will return just a few tips, or no tips (see this question in [FAQ](https://github.com/microsoft/azure-sql-tips/wiki/FAQ#i-ran-the-script-and-didnt-get-any-tips-is-something-wrong)). 

Currently, the script is written for SQL DB, there are no MI-specific tips (see [here](https://github.com/microsoft/azure-sql-tips/wiki/FAQ#does-it-work-on-azure-sql-managed-instance-or-on-sql-server)). This may change in the future (ideas for MI-specific tips are welcome), and in that case we should indeed add an `applies_to` column. If you think we should do it even now when the only values would be "SQLDB" and "SQLDB/SQLMI", we could consider that too.

**Comment by wsmelton** [comment]
I'd likely go ahead and add the applies column now. This will help on the command for dbatools and give a nice filter that can be used with PowerShell output.

Identify which level the tips applies might be useful but may not be, have not run this on service I have higher privileges on yet.

**Comment by dimitri-furman** [comment]
Regarding `applies_to`, can you clarify how that will help? I.e. if you run the script on DB, what's the usefulness in seeing that some returned tips happen to also apply to MI? And if you run it on MI, `applies_to` will be "SQLDB/SQLMI" by definition. Perhaps I am not seeing the scenario for this, an example will help.

Regarding permissions, this is a little bit more nuanced. Required permissions depend on the service objective. For Basic, S0, S1, and for all elastic pools, you do need VIEW **SERVER** STATE (thus server level access, though not necessarily server admin access, see Permissions in wiki) to query nearly all DMVs used in the script. I am not sure that it would be worthwhile running the script at all in that case if we only have VIEW DATABASE STATE - the output will be a long list of tips not evaluated due to insufficient permissions.

**Comment by wsmelton** [comment]
Just one right off...

Supporting the ability to use that SQL script in other tools as well or just in dbatools we support the ability to provide multiple servers and we execute that code against all of them. We format the output of SQL scripts to return a consistent output object or dataset. 

If the user is running it across their enterprise of servers (Azure SQL DB/MIs) we could include a custom property that we maintain, but having the raw script handle that functionality makes it more consistent when another tool is used.

**Comment by wsmelton** [comment]
As a full example...I ran this against a database (that sadly I only have access to the DB and not server level but adjusted it where it would at least return something)...

This is the base output of the version I used:
![image](https://user-images.githubusercontent.com/11204251/104625386-55b67b80-565a-11eb-86c7-629674d2af2e.png)

Within dbatools, we will inject a set of base properties: 
- ComputerName
- InstanceName
- SqlInstance

I can inject another one such as `ServiceType` that injects either `Azure SQL DB` or `Azure SQL MI` (or the short terms you provided). This allows when users pass in 2 or 3 server names that may be mixed to filter based on just those easily. The alternative is they have to call the command 2 or 3 times vs. one.

Some of this is also to cover less experienced users that see the script and want to utilize it in their enterprise but are not aware of all the exact differences between SQL DB and SQL MI. I would see this script as something I might use when I'm brought into new environments or new DBAs are brought in to start managing an already existing environment. Being able to identify which tip is for both or each just makes it easier to focus from my point of view.

**Comment by dimitri-furman** [comment]
The last point is reasonable, we will add that column to the result.

Just to be clear, this will be purely informational. Nothing in the script logic will change based on whether it is running on DB or MI, so I am not sure how this new column will be useful in the dbatools scenario you described. In other words, regardless of platform (DB or MI), each produced tip will be relevant, so no additional filtering of the result set should be done.

**Comment by dimitri-furman** [comment]
Linked PR adds support for returning at least some tips when you only have VIEW DATABASE STATE permission. There is a second result set returned listing the tips that weren't evaluated because of insufficient permissions. Please give this a try (just copy the latest code from the dfurman-dev-1 branch, there is not a release for this yet).

More on the `applies_to`: We can add the column to the tip definition table (@TipDefinition), which would make the code self-documenting, a useful thing from that viewpoint, but nothing more than that. I have a concern including this column in the output though. If a less experienced user sees that a tip applies to e.g. SQL DB, they might get an impression that it applies to *all* of SQL DB databases they have (or perhaps all similar databases, i.e. across different environments), while in reality it would only apply to the database where the script ran.

Also, if/when we add full support for MI tips, we are likely to do that in a separate script anyway; I expect the code will be substantially simpler that way compared to a lot of conditional processing. In that case, we'd need to deprecate this column, which could be problematic. 

So for now I am leaning towards not adding that column, at least not until there is a clear scenario where it will be useful. Admittedly, I may not fully understand the dbatools scenario you mentioned (e.g. I don't understand what "inject a set of base properties" means in this context - not a PowerShell dev here). If you think I missed your point, please elaborate.

Thanks again for feedback and suggestions, please keep them coming.
