### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by JanosBerke** [microsoft/azure-sql-tips#37]
When I try to run the script I got the following errors:
Msg 102, Level 15, State 1, Line 483
Incorrect syntax near 'WITHIN'.
Msg 102, Level 15, State 1, Line 662
Incorrect syntax near 'WITHIN'.
Msg 102, Level 15, State 1, Line 738
Incorrect syntax near 'WITHIN'.
Msg 102, Level 15, State 1, Line 762
Incorrect syntax near '('.
Msg 102, Level 15, State 1, Line 834
Incorrect syntax near 'WITHIN'.
Msg 102, Level 15, State 1, Line 900
Incorrect syntax near '('.
Msg 102, Level 15, State 1, Line 1092
Incorrect syntax near 'WITHIN'.
Msg 102, Level 15, State 1, Line 1321
Incorrect syntax near 'WITHIN'.
Msg 102, Level 15, State 1, Line 1477
Incorrect syntax near '('.
Msg 102, Level 15, State 1, Line 1648
Incorrect syntax near '('.
Msg 102, Level 15, State 1, Line 1684
Incorrect syntax near '('.
Msg 102, Level 15, State 1, Line 2299
Incorrect syntax near '('.
Msg 102, Level 15, State 1, Line 2641
Incorrect syntax near 'WITHIN'.

**Comment by dimitri-furman** [comment]
Thanks for testing. This is because the database is using compatibility level 100, which is not supported without a manual modification of the script. See [Limitations](https://github.com/microsoft/azure-sql-tips/wiki/Azure-SQL-Database-tips#limitations). 

We'll try to add a more descriptive error to raise in that case.

**Comment by dimitri-furman** [comment]
We added a separate version of the script for databases using compatibility level 100.

**Comment by JanosBerke** [comment]
Thank you 👍
